### ISSUE TITLE
Спасибо!

### ISSUE THREAD

**Issue by vaszol** [mymbrooks/VLCAndroidDemo#1]
Привет!
Спасибо за понятный рабочий код! Наконец-то я смогу перейти со старой версии этой библиотеки , теперь я понял что я делал не так!)

**Comment by mymbrooks** [comment]
Sorry for late reply, I'm very happy this demo can help you : )

**Comment by iikk** [comment]
很感谢你写的demo，他播放本地视频没什么问题，但播放云端视频就会出现画面卡顿，而声音一直是流畅的；播放直播时，什么反应都没有；右下角全屏，点击过后，显示就成乱码了（全屏乱码短一点，退出全屏乱码长一点）。
谢谢你的分享：)

远程视频：
http://200020860.vod.myqcloud.com/200020860_485c8b2a636911e6a779dd8dace58217.f20.mp4
直播流：rtmp://live.hkstv.hk.lxdns.com/live/hks

**Comment by mymbrooks** [comment]
我测试了你给的两个远程视频，都可以播放，速度也不慢。可能和你的手机型号、硬件配置、安卓版本有关，具体你看下调试信息，VLC 会有很多日志。
